function proiect(A,f,N,S,Rg,Rs,C1,C2,B,Vp,Val,I)
Id=I;
Vgs=round(vgs_calcul(Vp,B,Id),3);
Vds=round(vds_calcul(Val,Vgs),3);
gm=round(gm_calcul(B,Id),3);
Av=round(Av_calcul(gm,Rs),3);
Ri=Rg;
Ro=round(Ro_calcul(gm,Rs),3);
fig=figure('Name','Tranzistor Mos DC',...
            'Units','normalized',...
            'Position',[0 0.05 1 0.85],...
            'NumberTitle','off','color','w');
        
Doc=uimenu('Label','Documentatie');
prez_=uimenu(Doc,'Label','Prezentare','Callback','open prezentare.pptx','Separator','on');
prez_=uimenu(Doc,'Label','Autor','Callback','open autor.pdf','Separator','on');
 c_teo =uimenu(Doc,'Label','Considerente Teoretice','Separator','on');
 c_teo_f=uimenu(c_teo,'Label','Formule', 'Callback', 'open Formule.pdf');
 c_teo_s_=uimenu(c_teo,'Label','Circuite', 'Callback', 'open circuit1.pdf');
 c_teo_e=uimenu(c_teo,'Label','Exemple', 'Callback', 'open Exemplu.pdf');
 c_teo_u=uimenu(c_teo,'Label','Unitati de masura', 'Callback', 'open unitati_masura.pdf');
 bib=uimenu(Doc,'Label','Bibliografie','Callback','open Bibliografie.pdf','Separator','on');
 close= uimenu(Doc,'Label','Close','Callback','close','Separator','on','Accelerator','Q');
 
 PVi=uibuttongroup('Visible','on',...
                  'BackgroundColor',[0.75,0.75,0.75],...
                  'ForegroundColor','black',...
                  'Title','Vi',...
                  'FontSize',10,...
                  'TitlePosition','centertop',...
                  'Tag','PVi',...
                  'Position',[0.05 0.85 0.22 0.1]);
AVt=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Amplitudine',...
                'Position', [0.05 .45 .2 .4],...
                'parent',PVi);
fVt=uicontrol('Style','text',...
                'Units','normalized',...
                'String','frecventa',...
                'Position', [0.05 .05 .2 .4],...
                'parent',PVi);
AVe=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',A,...
                'Value',A,...
                'Position', [0.25 .45 .2 .4],...
                'Callback',['A=','str2num(get(gco,''String''))'],...
                'parent',PVi);
fVe=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',f,...
                'Position', [0.25 .05 .2 .4],...
                'Callback',['f=','str2num(get(gco,''String''))'],...
                'parent',PVi);
NVt=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Perioada N',...
                'Position', [0.5 .5 .2 .4],...
                'parent',PVi);
NVe=uicontrol('Style','popupmenu',...
                'Units','normalized',...
                'Position', [0.5 .1 .2 .4],...
                'String','1| 2| 3| 4| 5| 6| 7| 8| 9| 10',...
                'Value',N,...
                'Callback','N=get(gco,''Value'')',...
                'parent',PVi);
SVt=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Semnal',...
                'Position', [0.75 .5 .2 .4],...
                'parent',PVi);
SVe=uicontrol('Style','popupmenu',...
                'Units','normalized',...
                'Position', [0.75 .1 .2 .4],...
                'String','sinus|cosinus|triunghi|dreptunghi',...
                'Value',S,...
                'Callback','S=get(gco,''Value'')',...
                'parent',PVi);
Valori=uibuttongroup('Visible','on',...
                  'BackgroundColor',[0.75,0.75,0.75],...
                  'ForegroundColor','black',...
                  'FontSize',10,...
                  'Title','Parametri',...
                  'TitlePosition','centertop',...
                  'Tag','Valori',...
                  'Position',[0.05 0.48 0.22 0.35]);
T1=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Rs',...
                'Position', [0.05 .75 .15 .15],...
                'parent',Valori);
T2=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Rg',...
                'Position', [0.05 .55 .15 .15],...
                'parent',Valori);
T3=uicontrol('Style','text',...
                'Units','normalized',...
                'String','C1',...
                'Position', [0.05 .35 .15 .15],...
                'parent',Valori);
T4=uicontrol('Style','text',...
                'Units','normalized',...
                'String','C2',...
                'Position', [0.05 .15 .15 .15],...
                'parent',Valori);
E1=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',Rs,...
                'Position', [0.25 .75 .15 .15],...
                'Callback',['Rs=','str2num(get(gco,''String''))'],...
                'parent',Valori);
E2=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',Rg,...
                'Position', [0.25 .55 .15 .15],...
                'Callback',['Rg=','str2num(get(gco,''String''))'],...
                'parent',Valori);
E3=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',C1,...
                'Position', [0.25 .35 .15 .15],...
                'Callback',['C1=','str2num(get(gco,''String''))'],...
                'parent',Valori);
E4=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',C2,...
                'Position', [0.25 .15 .15 .15],...
                'Callback',['C2=','str2num(get(gco,''String''))'],...
                'parent',Valori);
T5=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Beta',...
                'Position', [0.6 .75 .15 .15],...
                'parent',Valori);
T6=uicontrol('Style','text',...
                'Units','normalized',...
                'String','+/-Val',...
                'Position', [0.6 .55 .15 .15],...
                'parent',Valori);
T7=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Vp',...
                'Position', [0.6 .35 .15 .15],...
                'parent',Valori);
T8=uicontrol('Style','text',...
                'Units','normalized',...
                'String','I',...
                'Position', [0.6 .15 .15 .15],...
                'parent',Valori);

E5=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',B,...
                'Position', [0.8 .75 .15 .15],...
                'Callback',['B=','str2num(get(gco,''String''))'],...
                'parent',Valori);
E6=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',Val,...
                'Position', [0.8 .55 .15 .15],...
                'Callback',['Val=','str2num(get(gco,''String''))'],...
                'parent',Valori);
E7=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',Vp,...
                'Position', [0.8 .35 .15 .15],...
                'Callback',['Vp=','str2num(get(gco,''String''))'],...
                'parent',Valori);
E8=uicontrol('Style','edit',...
                'Units','normalized',...
                'String',I,...
                'Position', [0.8 .15 .15 .15],...
                'Callback',['I=','str2num(get(gco,''String''))'],...
                'parent',Valori);
Pst=uibuttongroup('Visible','on',...
                  'BackgroundColor',[0.75,0.75,0.75],...
                  'ForegroundColor','black',...
                  'Title','Punctul static Q',...
                  'FontSize',10,...
                  'TitlePosition','centertop',...
                  'Tag','Pst',...
                  'Position',[0.05 0.365 0.22 0.1]);
Ide=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Id',...
                'Position', [0.25 0.55 .2 .4],...
                'parent',Pst);
Vdse=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Vds',...
                'Position', [0.50 .55 .2 .4],...
                'parent',Pst);
Idt=uicontrol('Style','text',...
                'Units','normalized',...
                'String',Id,...
                'Position', [0.25 .05 .2 .4],...
                'parent',Pst);
Vdst=uicontrol('Style','text',...
                'Units','normalized',...
                'String',Vds,...
                'Position', [0.50 .05 .2 .4],...
                'parent',Pst);
Vcalc=uibuttongroup('Visible','on',...
                  'BackgroundColor',[0.75,0.75,0.75],...
                  'ForegroundColor','black',...
                  'Title','Valori Calculate',...
                  'FontSize',10,...
                  'TitlePosition','centertop',...
                  'Tag','Pst',...
                  'Position',[0.05 0.245 0.22 0.1]);
Ave=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Av',...
                'Position', [0.05 0.55 .15 .4],...
                'parent',Vcalc);
gme=uicontrol('Style','text',...
                'Units','normalized',...
                'String','gm',...
                'Position', [0.25 .55 .15 .4],...
                'parent',Vcalc);
Avt=uicontrol('Style','text',...
                'Units','normalized',...
                'String',Av,...
                'Position', [0.05 .05 .15 .4],...
                'parent',Vcalc);
gmt=uicontrol('Style','text',...
                'Units','normalized',...
                'String',gm,...
                'Position', [0.25 .05 .15 .4],...
                'parent',Vcalc);
Rit=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Ri',...
                'Position', [0.55 .55 .15 .4],...
                'parent',Vcalc);
Rot=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Ro',...
                'Position', [0.75 .55 .15 .4],...
                'parent',Vcalc);
Rie=uicontrol('Style','text',...
                'Units','normalized',...
                'String',Ri,...
                'Position', [0.55 .05 .15 .4],...
                'parent',Vcalc);
Roe=uicontrol('Style','text',...
                'Units','normalized',...
                'String',Ro,...
                'Position', [0.75 .05 .15 .4],...
                'parent',Vcalc);
Set=uicontrol('Style','pushbutton',...  
    'Units','normalized',...            
    'Position',[0.05 0.10 0.22 0.1],...
    'String','Seteaza',...       
    'FontSize',15,...
    'Callback','close;proiect(A,f,N,S,Rg,Rs,C1,C2,B,Vp,Val,I)'); 

Textimg1=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Schema Amplificatorului T-Mos ',...
                'FontSize', 12,...
                'BackgroundColor','white',...
                'ForegroundColor','b',...
                'Position', [0.3216 0.0155 .255 .035]);
Textimg2=uicontrol('Style','text',...
                'Units','normalized',...
                'String','Schema în curent continuu',...
                'FontSize', 12,...
                'BackgroundColor','white',...
                'ForegroundColor','b',...
                'Position', [0.728 0.015 .144 .035]);
axes('pos',[.20 .05 .5 .35])
imshow('schema2.jpg');
axes('pos',[.55 .05 .5 .35])
imshow('schema1.jpg');

if N==2
   set(fig,'color', '[0.8 0.4 0]')
elseif N==3
   set(fig,'color','[0.9 0.2 0]')
elseif N==4
   set(fig,'color','[0 0.5 0.1]')
elseif N==5
   set(fig,'color','[0.3 0.4 0.4]')
elseif N==6
   set(fig,'color','[1 0.2 0.3]')
elseif N==7
   set(fig,'color','[0.7 1 0.9]')
elseif N==8
   set(fig,'color','[0.4 0.5 0.6]')
elseif N==9
   set(fig,'color','[0.6 0.8 0.5]')
elseif N==10
   set(fig,'color','[1 0.8 0.3]')
else
    set(fig,'color','[0.9 0.4 0.4]')
end
format long
T=1/f;
t=0:T/50:N*T;
if S==1
    vi=A.*sin(2*pi*f*t);
elseif S==2
    vi=A.*cos(2*pi*f*t);
elseif S==3
    vi =A.*sawtooth(2*pi*f*t,0.5);
elseif S==4
    vi =A.*sawtooth(2*pi*f*t);
else
    vi =A.*square(2*pi*f*t);
end

if A<Vp
    axes('pos',[.35 .5 .55 .45])
    imshow('blocare.jpg');
else 
    subplot('Position', [0.35 0.5 0.55 0.45])
    vo=Av.*vi;
    plot(t,vi,'-g','LineWidth',3); 
    hold on;
    grid on;
    plot(t,vo,'--k', 'LineWidth',2);
    hold on;
    grid on;
    xlabel('timp [s]');
    ylabel('Tensiunea [V]');
    legend('Vi','Vo');
end


end